/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package barcodeclass;

import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Janine
 */
public class AddAdminForm extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public AddAdminForm(JFrame f) {
        this.parent=(AdminsForm) f;
        initComponents();
        showAdmins();
        jLabel2.setVisible(false);
        jLabel3.setVisible(false);
        user.setVisible(false);
        pword.setVisible(false);
        this.setLocationRelativeTo(null);
        this.setVisible(true);
    }
    
    Connection con;
    PreparedStatement pst;
    ResultSet rs;
    DefaultTableModel adminmdl=new DefaultTableModel();
    AdminsForm parent;
    void showAdmins(){
        try{
            settbl();
            con=DriverManager.getConnection("jdbc:sqlite:src//mainDB.db");
            pst=con.prepareStatement("SELECT*FROM Adminstbl");
            rs=pst.executeQuery();
            Object ad[]=new Object[2];
            while(rs.next()){
               ad[0]=rs.getString("Username");
               ad[1]=rs.getString("Password");
               adminmdl.addRow(ad);
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }
    void settbl(){
        String[] columns={"Username","Password"};
        adminmdl.setColumnIdentifiers(columns);
        admintbl.setModel(adminmdl);
        for(int i=0; i<admintbl.getColumnCount();i++){
            admintbl.setDefaultEditor(admintbl.getColumnClass(i), null);
        }
        admintbl.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        scrollpane.getViewport().setBackground(new Color(0,204,204));
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainpanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        scrollpane = new javax.swing.JScrollPane();
        admintbl = new javax.swing.JTable();
        newbtn = new javax.swing.JButton();
        updatebtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        user = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        pword = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        mainpanel.setBackground(new java.awt.Color(0, 204, 204));
        mainpanel.setRequestFocusEnabled(false);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Admins");
        jLabel1.setMaximumSize(new java.awt.Dimension(347, 35));
        jLabel1.setMinimumSize(new java.awt.Dimension(347, 35));
        jLabel1.setName(""); // NOI18N
        jLabel1.setPreferredSize(new java.awt.Dimension(347, 35));

        scrollpane.setBackground(new java.awt.Color(0, 204, 204));
        scrollpane.setBorder(null);
        scrollpane.setPreferredSize(new java.awt.Dimension(322, 85));

        admintbl.setBackground(new java.awt.Color(153, 102, 255));
        admintbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        admintbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                admintblMouseClicked(evt);
            }
        });
        scrollpane.setViewportView(admintbl);

        newbtn.setBackground(new java.awt.Color(102, 255, 102));
        newbtn.setText("New");
        newbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newbtnActionPerformed(evt);
            }
        });

        updatebtn.setBackground(new java.awt.Color(255, 153, 51));
        updatebtn.setText("Edit");
        updatebtn.setEnabled(false);
        updatebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatebtnActionPerformed(evt);
            }
        });

        jLabel2.setText("Username:");

        user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userActionPerformed(evt);
            }
        });

        jLabel3.setText("Password:");

        pword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pwordActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 51, 51));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("X");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout mainpanelLayout = new javax.swing.GroupLayout(mainpanel);
        mainpanel.setLayout(mainpanelLayout);
        mainpanelLayout.setHorizontalGroup(
            mainpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainpanelLayout.createSequentialGroup()
                .addGroup(mainpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainpanelLayout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(newbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(updatebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(mainpanelLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(mainpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(scrollpane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(mainpanelLayout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(user))
                            .addGroup(mainpanelLayout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(pword)))))
                .addGap(10, 10, 10))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainpanelLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        mainpanelLayout.setVerticalGroup(
            mainpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainpanelLayout.createSequentialGroup()
                .addGroup(mainpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(scrollpane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(mainpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(user, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(mainpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(mainpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(updatebtn)
                    .addComponent(newbtn))
                .addGap(12, 12, 12))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainpanel, javax.swing.GroupLayout.PREFERRED_SIZE, 341, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void newbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newbtnActionPerformed
        if(newbtn.getText().equals("New")){
            jLabel2.setVisible(true);
            jLabel3.setVisible(true);
            user.setVisible(true);
            pword.setVisible(true);
            newbtn.setText("Add");
            updatebtn.setEnabled(false);
        }
        else{
            if(!user.getText().trim().equals("") && !pword.getText().trim().equals("")){
            try{
                con=DriverManager.getConnection("jdbc:sqlite:src//mainDB.db");
                pst=con.prepareStatement("INSERT INTO Adminstbl(Username,Password) VALUES(?,?)");
                pst.setString(1, user.getText());
                pst.setString(2, pword.getText());
                pst.executeUpdate();
                user.setText("");
                pword.setText("");
                jLabel2.setVisible(false);
                jLabel3.setVisible(false);
                user.setVisible(false);
                pword.setVisible(false);
                newbtn.setText("New");
                adminmdl.setRowCount(0);
                showAdmins();
            }
            catch(Exception e){
                e.printStackTrace();
            }
            }
            else{
                JOptionPane.showMessageDialog(rootPane, "Invalid Username or Password");
            }
        }
    }//GEN-LAST:event_newbtnActionPerformed

    private void updatebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatebtnActionPerformed
        String old=admintbl.getValueAt(admintbl.getSelectedRow(), 0).toString();
        if(updatebtn.getText().equals("Edit")){
            jLabel2.setVisible(true);
            jLabel3.setVisible(true);
            user.setVisible(true);
            pword.setVisible(true);
            user.setText(admintbl.getValueAt(admintbl.getSelectedRow(), 0).toString());
            pword.setText(admintbl.getValueAt(admintbl.getSelectedRow(), 1).toString());
            updatebtn.setText("Save");
            newbtn.setEnabled(false);
            newbtn.setText("New");
        }
        
        else if(updatebtn.getText().equals("Save")&& !user.getText().trim().equals("") && !pword.getText().trim().equals("")){
            try{
                con=DriverManager.getConnection("jdbc:sqlite:src//mainDB.db");
                pst=con.prepareStatement("UPDATE Adminstbl SET Username=?,Password=? WHERE Username='"+old+"'");
                pst.setString(1, user.getText());
                pst.setString(2, pword.getText());
                pst.executeUpdate();
                user.setText("");
                pword.setText("");
                jLabel2.setVisible(false);
                jLabel3.setVisible(false);
                user.setVisible(false);
                pword.setVisible(false);
                updatebtn.setText("Edit");
                updatebtn.setEnabled(false);
                newbtn.setEnabled(true);
                adminmdl.setRowCount(0);
                showAdmins();
            }
            catch(Exception e){
                e.printStackTrace();
            }
        }
        else{
            JOptionPane.showMessageDialog(rootPane, "Invalid Username or Password");
        }
    }//GEN-LAST:event_updatebtnActionPerformed

    private void userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userActionPerformed
        pword.requestFocus();
    }//GEN-LAST:event_userActionPerformed

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        parent.setEnabled(true);
        parent.requestFocus();
        this.dispose();
    }//GEN-LAST:event_jLabel4MouseClicked

    private void pwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pwordActionPerformed
        if(updatebtn.isEnabled())
            updatebtn.doClick();
        else
            newbtn.doClick();
    }//GEN-LAST:event_pwordActionPerformed

    private void admintblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_admintblMouseClicked
        if(admintbl.getSelectedRowCount()==1){
            updatebtn.setEnabled(true);
        }
    }//GEN-LAST:event_admintblMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddAdminForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddAdminForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddAdminForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddAdminForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               new AddAdminForm(new JFrame()).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable admintbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel mainpanel;
    private javax.swing.JButton newbtn;
    private javax.swing.JTextField pword;
    private javax.swing.JScrollPane scrollpane;
    private javax.swing.JButton updatebtn;
    private javax.swing.JTextField user;
    // End of variables declaration//GEN-END:variables
}
