/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package barcodeclass;

import java.sql.*;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author Janine
 */
public class AddReturnedItemForm extends javax.swing.JFrame {

    /**
     * Creates new form AddReturnedItemForm
     */
    public AddReturnedItemForm(AdminsForm f) {
        initComponents();
        this.parent=f;
        this.setLocationRelativeTo(null);
        this.setVisible(true);
    }
    
    AdminsForm parent;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        closeretItemsFormlbl = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        receiptfld = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        salesidfld = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        itemcodefld = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        numunitfld = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        saveritembtn = new javax.swing.JButton();
        datepicker = new org.jdesktop.swingx.JXDatePicker();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(204, 0, 204));

        jLabel1.setText("Returned Items");

        closeretItemsFormlbl.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        closeretItemsFormlbl.setForeground(new java.awt.Color(255, 0, 0));
        closeretItemsFormlbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        closeretItemsFormlbl.setText("X");
        closeretItemsFormlbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeretItemsFormlblMouseClicked(evt);
            }
        });

        jLabel2.setText("Receipt #:");

        receiptfld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                receiptfldActionPerformed(evt);
            }
        });

        jLabel3.setText("Sales ID:");

        salesidfld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salesidfldActionPerformed(evt);
            }
        });

        jLabel4.setText("Item Code:");

        itemcodefld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemcodefldActionPerformed(evt);
            }
        });

        jLabel5.setText("# of Units:");

        numunitfld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numunitfldActionPerformed(evt);
            }
        });

        jLabel6.setText("Date of Return:");

        saveritembtn.setBackground(new java.awt.Color(255, 153, 51));
        saveritembtn.setText("Save");
        saveritembtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveritembtnActionPerformed(evt);
            }
        });

        datepicker.setDate(new java.util.Date());
        datepicker.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                datepickerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(salesidfld))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(receiptfld))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(itemcodefld))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(numunitfld))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(datepicker, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                        .addGap(18, 18, 18)
                        .addComponent(closeretItemsFormlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(saveritembtn, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(closeretItemsFormlbl, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(receiptfld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(salesidfld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(itemcodefld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numunitfld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(datepicker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(saveritembtn)
                .addContainerGap(56, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeretItemsFormlblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeretItemsFormlblMouseClicked
        parent.setEnabled(true);
        parent.requestFocus();
        this.dispose();
    }//GEN-LAST:event_closeretItemsFormlblMouseClicked

    private void datepickerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_datepickerActionPerformed
        saveritembtn.doClick();
    }//GEN-LAST:event_datepickerActionPerformed

    private void receiptfldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_receiptfldActionPerformed
        salesidfld.requestFocus();
    }//GEN-LAST:event_receiptfldActionPerformed

    private void salesidfldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salesidfldActionPerformed
        itemcodefld.requestFocus();
    }//GEN-LAST:event_salesidfldActionPerformed

    private void itemcodefldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemcodefldActionPerformed
        numunitfld.requestFocus();
    }//GEN-LAST:event_itemcodefldActionPerformed

    private void numunitfldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numunitfldActionPerformed
        datepicker.requestFocus();
    }//GEN-LAST:event_numunitfldActionPerformed

    private void saveritembtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveritembtnActionPerformed
        Connection con;
        PreparedStatement pst;
        ResultSet rs;
        int rcptid=0,salesid=0,unitq=0;
        String rid=receiptfld.getText().trim();
        String sid=salesidfld.getText().trim();
        String itemcode=itemcodefld.getText().trim();
        String unit=numunitfld.getText().trim();
        java.util.Date dreturn=new java.util.Date();
        boolean save1=false;
        boolean save2=false;
        boolean save3=false;
        
        if(rid.equals("")||sid.equals("")||itemcode.equals("")||unit.equals("")){
            JOptionPane.showMessageDialog(this, "All fields are required!");
        }  
        else{
            try{
                try{
                    rcptid=Integer.parseInt(rid);
                    save1=true;
                }
                catch(Exception e){
                    JOptionPane.showMessageDialog(rootPane, "Invalid Receipt ID!");
                }
                try{
                    salesid=Integer.parseInt(sid);
                    save2=true;
                }
                catch(Exception e){
                    JOptionPane.showMessageDialog(rootPane, "Invalid Sales ID!");
                }
                try{
                    unitq=Integer.parseInt(unit);
                    save3=true;
                }
                catch(Exception e){
                    JOptionPane.showMessageDialog(rootPane, "Invalid # of Units");
                }
                try{
                    dreturn=datepicker.getDate();
                }
                catch(Exception e){
                    dreturn=new java.util.Date();
                }

                if(save1 && save2 && save3){
                    int rem=0,sold=0;
                    int itemid=0,priceid=0,stockid=0;
                    float totalref=0.0f;
                    con=DriverManager.getConnection("jdbc:sqlite:src//mainDB.db");
                    
                    String qry="SELECT Quantity,Unit_Price FROM Salestbl WHERE Sales_ID='"+salesid+"'";
                    pst=con.prepareStatement(qry);
                    rs=pst.executeQuery();
                    rs.next();
                    int sqty=rs.getInt("Quantity");
                    float sunitp=rs.getFloat("Unit_Price");
                    if(sqty==0)
                        JOptionPane.showMessageDialog(parent, "Incorrect Sales_ID");
                    else{
                        qry="SELECT Item_ID,Price_ID,Stock_ID FROM Itemstbl WHERE Item_Code='"+itemcode+"'";
                        pst=con.prepareStatement(qry);
                        rs=pst.executeQuery();
                        rs.next();
                        itemid=rs.getInt("Item_ID");
                        priceid=rs.getInt("Price_ID");
                        stockid=rs.getInt("Stock_ID");
                        
                        qry="SELECT * FROM Quantitytbl WHERE Stock_ID='"+stockid+"'";
                        pst=con.prepareStatement(qry);
                        rs=pst.executeQuery();
                        rs.next();
                        rem=rs.getInt("Remaining")+unitq;
                        sold=rs.getInt("Sold")-unitq;
                    
                        qry="SELECT Selling_Price FROM Pricetbl WHERE Price_ID='"+priceid+"'";
                        pst=con.prepareStatement(qry);
                        rs=pst.executeQuery();
                        rs.next();
                        totalref=rs.getFloat("Selling_Price")*unitq;

                        qry="UPDATE Quantitytbl SET Sold=?,Remaining=? WHERE Stock_ID='"+stockid+"'";
                        pst=con.prepareStatement(qry);
                        pst.setInt(1, sold);
                        pst.setInt(2, rem);
                        pst.executeUpdate();
                        
                        qry="UPDATE Salestbl SET Quantity=?,Total_Amount=? WHERE Item_ID='"+itemid+"'";
                        pst=con.prepareStatement(qry);
                        pst.setInt(1, sqty-unitq);
                        pst.setFloat(2, (sqty-unitq)*sunitp);
                        pst.executeUpdate();

                        qry="INSERT INTO ReturnedItemstbl(Sales_ID,Units_Returned,Total_Refund,Date_Returned) VALUES(?,?,?,?)";
                        pst=con.prepareStatement(qry);
                        pst.setInt(1, salesid);
                        pst.setInt(2, unitq);
                        pst.setFloat(3, totalref);
                        pst.setString(4, new SimpleDateFormat("MM/dd/yyyy").format(dreturn));
                        pst.executeUpdate();
                        con.close();

                        parent.setEnabled(true);
                        parent.itemsmodel.setRowCount(0);
                        parent.salesmodel.setRowCount(0);
                        parent.receiptsmodel.setRowCount(0);
                        parent.returneditemsmodel.setRowCount(0);
                        parent.updateAllTables();
                        parent.requestFocus();
                        this.dispose();
                    }
                }
            }
            catch(Exception e){
                e.printStackTrace();
                JOptionPane.showMessageDialog(parent, "Some inputs are Incorrect!");
            }
        }  
    }//GEN-LAST:event_saveritembtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddReturnedItemForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddReturnedItemForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddReturnedItemForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddReturnedItemForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new AddReturnedItemForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel closeretItemsFormlbl;
    private org.jdesktop.swingx.JXDatePicker datepicker;
    private javax.swing.JTextField itemcodefld;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField numunitfld;
    private javax.swing.JTextField receiptfld;
    private javax.swing.JTextField salesidfld;
    private javax.swing.JButton saveritembtn;
    // End of variables declaration//GEN-END:variables
}
