/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package barcodeclass;

import java.awt.image.BufferedImage;
import java.io.File;
import java.io.FileInputStream;
import java.nio.file.Files;
import java.nio.file.Paths;
import javax.imageio.ImageIO;
import javax.print.Doc;
import javax.print.DocFlavor;
import javax.print.DocPrintJob;
import javax.print.PrintService;
import javax.print.PrintServiceLookup;
import javax.print.SimpleDoc;
import javax.print.attribute.HashPrintRequestAttributeSet;
import javax.print.attribute.PrintRequestAttributeSet;
import javax.print.attribute.standard.Copies;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Janine
 */
public class PrintBarcodeDlg extends javax.swing.JFrame {

    /**
     * Creates new form PrintBarcodeDlg
     */
    public PrintBarcodeDlg(javax.swing.JDialog parent, File image, String copy) {
        this.parent=(AddItemDlg)parent;
        this.imagepath=image;
        initComponents();
        displayBcode(copy);
        this.setLocationRelativeTo(null);
        this.setVisible(true);
    }
    
    AddItemDlg parent;
    File imagepath;
    BufferedImage img;
    ImageIcon icon;
    boolean exported=false;
    int copies=1;
    
    void displayBcode(String copy){
        try{
            img=ImageIO.read(imagepath);
            icon=new ImageIcon(img);
            this.displaylbl.setIcon(icon);
            this.copyfld.setText(copy);
        }
        catch(Exception e){
            e.printStackTrace();
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        displaylbl = new javax.swing.JLabel();
        printbtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        copyfld = new javax.swing.JTextField();
        exportbtn = new javax.swing.JButton();
        closeprintbarcodedlg = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(51, 51, 255));

        displaylbl.setBackground(new java.awt.Color(153, 153, 153));
        displaylbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        displaylbl.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        displaylbl.setOpaque(true);

        printbtn.setBackground(new java.awt.Color(255, 153, 51));
        printbtn.setText("Print Barcode");
        printbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printbtnActionPerformed(evt);
            }
        });

        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Number of Copies to Print:");

        exportbtn.setBackground(new java.awt.Color(204, 102, 255));
        exportbtn.setText("Export As Image");
        exportbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exportbtnActionPerformed(evt);
            }
        });

        closeprintbarcodedlg.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        closeprintbarcodedlg.setForeground(new java.awt.Color(255, 0, 0));
        closeprintbarcodedlg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        closeprintbarcodedlg.setText("X");
        closeprintbarcodedlg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeprintbarcodedlgMouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Printing Barcode");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(copyfld, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE))
                    .addComponent(displaylbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(printbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(exportbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(20, 20, 20))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(closeprintbarcodedlg, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(closeprintbarcodedlg, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(displaylbl, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(copyfld))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(printbtn)
                .addGap(18, 18, 18)
                .addComponent(exportbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void printbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printbtnActionPerformed
        PrintRequestAttributeSet pras = new HashPrintRequestAttributeSet();
        try{
            copies=Integer.parseInt(copyfld.getText());
            if(copies>0){
                pras.add(new Copies(copies));
                PrintService pss[] = PrintServiceLookup.lookupPrintServices(DocFlavor.INPUT_STREAM.JPEG, pras);
                if (pss.length == 0)
                    JOptionPane.showMessageDialog(rootPane,"No Printer Availabel");
                PrintService ps = pss[0];
                JOptionPane.showMessageDialog(rootPane,"Printing to " + ps);
                DocPrintJob job = ps.createPrintJob();
                FileInputStream fin;
                fin = new FileInputStream(imagepath);
                Doc doc = new SimpleDoc(fin, DocFlavor.INPUT_STREAM.JPEG, null);
                job.print(doc, pras);
                fin.close();
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this, e);
        }
    }//GEN-LAST:event_printbtnActionPerformed

    private void exportbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exportbtnActionPerformed
        exported=true;
        JOptionPane.showMessageDialog(rootPane, "Successfully save as image file at\n"+imagepath);
    }//GEN-LAST:event_exportbtnActionPerformed

    private void closeprintbarcodedlgMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeprintbarcodedlgMouseClicked
        if(exported==false){
           int exp=JOptionPane.showConfirmDialog(rootPane, "Export Barcode As Image?","",JOptionPane.YES_NO_OPTION);
           if(exp==JOptionPane.YES_OPTION){
               exportbtn.doClick();
           }
           else{
               try{
                   Files.delete(Paths.get(imagepath.getAbsolutePath()));
               }
               catch(Exception e){
                   
               }
           }
        }
        parent.setEnabled(true);
        parent.requestFocus();
        this.dispose();
    }//GEN-LAST:event_closeprintbarcodedlgMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrintBarcodeDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrintBarcodeDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrintBarcodeDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrintBarcodeDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //PrintBarcodeDlg dialog = new PrintBarcodeDlg(new javax.swing.JFrame(), true);
                //dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                //    @Override
                //    public void windowClosing(java.awt.event.WindowEvent e) {
                //        System.exit(0);
                //    }
                //});
                //dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel closeprintbarcodedlg;
    private javax.swing.JTextField copyfld;
    private javax.swing.JLabel displaylbl;
    private javax.swing.JButton exportbtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton printbtn;
    // End of variables declaration//GEN-END:variables
}
